#!/bin/bash

CURRENT_DIR=$(dirname "$(readlink -f "$0")")
KERNEL_DIR=${CURRENT_DIR}/../../idg-lib/src/CUDA/common/kernels
KERNEL_FILE=$(realpath ${KERNEL_DIR}/KernelDegridder.cu)
echo "$0" ${KERNEL_FILE}
python ${CURRENT_DIR}/cuda-degridder.py --num-blocks 0 --file ${KERNEL_FILE}
