#!/bin/bash

CURRENT_DIR=$(dirname "$(readlink -f "$0")")
KERNEL_DIR=${CURRENT_DIR}/../../idg-lib/src/CUDA/common/kernels
KERNEL_FILE=$(realpath ${KERNEL_DIR}/KernelGridder.cu)
echo "$0" ${KERNEL_FILE}
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CUDA_ROOT/lib64 \
python3 ${CURRENT_DIR}/cuda-gridder.py --num-blocks 0 --file ${KERNEL_FILE}
