# - Try to find clFFT
# This module tries to find the clFFT library on your system
#
# Once done this will define
#  CLFFT_FOUND        - system has clFFT
#  CLFFT_INCLUDE_DIRS - the clFFT include directory
#  CLFFT_LIBRARIES    - link these to use clFFT

FIND_PACKAGE( PackageHandleStandardArgs )

# Unix style platforms
FIND_LIBRARY(CLFFT_LIBRARIES clFFT
    ${CMAKE_SOURCE_DIR}/lib/clFFT/lib64
    ENV LD_LIBRARY_PATH
)

GET_FILENAME_COMPONENT(CLFFT_LIB_DIR ${CLFFT_LIBRARIES} PATH)
GET_FILENAME_COMPONENT(_CLFFT_INC_CAND ${CLFFT_LIB_DIR}/../include ABSOLUTE)

# search for headers relative to the library
FIND_PATH(CLFFT_INCLUDE_DIRS clFFT.h PATHS ${_CLFFT_INC_CAND})
FIND_PATH(_CLFFT_CPP_INCLUDE_DIRS clFFT.h PATHS ${_CLFFT_INC_CAND})

FIND_PACKAGE_HANDLE_STANDARD_ARGS( clFFT DEFAULT_MSG CLFFT_LIBRARIES CLFFT_INCLUDE_DIRS )

IF( _CLFFT_CPP_INCLUDE_DIRS )
	SET( CLFFT_HAS_CPP_BINDINGS TRUE )
	LIST( APPEND CLFFT_INCLUDE_DIRS ${_CLFFT_CPP_INCLUDE_DIRS} )
	# This is often the same, so clean up
	LIST( REMOVE_DUPLICATES CLFFT_INCLUDE_DIRS )
ENDIF( _CLFFT_CPP_INCLUDE_DIRS )

MARK_AS_ADVANCED(
  CLFFT_INCLUDE_DIRS
)
