"""Execution-layer helpers for Rapthor's Prefect/Dask runtime.

This broad package facade is kept for migration-era compatibility. New code
should prefer imports from the module that owns the behaviour.
"""

from rapthor.execution.capabilities import (
    PreflightError,
    PreflightIssue,
    collect_preflight_issues,
    preflight_execution,
)
from rapthor.execution.commands import command_matches_fixture, command_to_string, normalize_command
from rapthor.execution.config import (
    DASK_SCHEDULER_ENV,
    ExecutionConfig,
    dask_scheduler_from_environment,
)
from rapthor.execution.flows.calibrate import (
    calibrate_chunk_task,
    calibrate_flow,
    calibrate_payload_from_inputs,
    run_calibrate_chunk,
    run_calibrate_flow,
)
from rapthor.execution.flows.concatenate import (
    build_concatenate_command,
    concatenate_epoch_task,
    concatenate_flow,
    concatenate_payload_from_inputs,
    normalized_concatenate_command,
    run_concatenate_epoch,
    run_concatenate_flow,
)
from rapthor.execution.flows.image import (
    image_flow,
    image_sector_task,
    run_image_flow,
)
from rapthor.execution.flows.mosaic import (
    build_compress_mosaic_command,
    build_make_mosaic_command,
    build_make_mosaic_template_command,
    build_regrid_image_command,
    mosaic_flow,
    mosaic_image_type_task,
    mosaic_payload_from_inputs,
    normalized_make_mosaic_command,
    normalized_make_mosaic_template_command,
    normalized_regrid_image_command,
    run_mosaic_flow,
    run_mosaic_image_type,
)
from rapthor.execution.flows.predict import (
    build_add_sector_models_command,
    build_predict_model_data_command,
    build_subtract_sector_models_command,
    normalized_add_sector_models_command,
    normalized_predict_model_data_command,
    normalized_subtract_sector_models_command,
    predict_flow,
    predict_model_data_task,
    predict_payload_from_inputs,
    predict_postprocess_task,
    run_predict_flow,
    run_predict_model_data,
    run_predict_postprocess,
)
from rapthor.execution.flows.process import (
    SUPPORTED_PROCESS_FEATURES,
    ProcessLifecycleHooks,
    ProcessOperationFactories,
    collect_process_features,
    default_process_lifecycle_hooks,
    default_process_operation_factories,
    process_flow,
    process_steps_flow,
    run_process,
    run_process_preflight,
    run_process_steps,
)
from rapthor.execution.outputs import (
    OutputRecordError,
    directory_record,
    file_record,
    is_output_record,
    validate_output_record,
)
from rapthor.execution.payloads import PayloadSerializationError, assert_serializable_payload
from rapthor.execution.resources import (
    ResourceRequest,
    collect_resource_issues,
    collect_resource_request_issues,
    validate_resource_request,
)
from rapthor.execution.runtime import RuntimeSpec, UnsupportedRuntimeError, build_runtime_spec
from rapthor.execution.shell import MissingPrefectShellError, ShellCommand, run_shell_command
from rapthor.execution.slurm import (
    SLURM_CPUS_PER_TASK_ENV,
    SLURM_NODE_COUNT_ENV,
    SLURM_TASK_COUNT_ENV,
    SlurmClusterSpec,
    collect_slurm_config_issues,
    slurm_cluster_spec,
)
from rapthor.execution.task_runner import (
    DaskSchedulerConnectionError,
    MissingPrefectDaskError,
    build_task_runner,
    check_dask_scheduler,
)
from rapthor.execution.workdirs import WorkDirectoryLayout

__all__ = [
    "DASK_SCHEDULER_ENV",
    "DaskSchedulerConnectionError",
    "ExecutionConfig",
    "MissingPrefectDaskError",
    "MissingPrefectShellError",
    "OutputRecordError",
    "PayloadSerializationError",
    "PreflightError",
    "PreflightIssue",
    "ProcessLifecycleHooks",
    "ProcessOperationFactories",
    "ResourceRequest",
    "RuntimeSpec",
    "ShellCommand",
    "SLURM_CPUS_PER_TASK_ENV",
    "SLURM_NODE_COUNT_ENV",
    "SLURM_TASK_COUNT_ENV",
    "SUPPORTED_PROCESS_FEATURES",
    "SlurmClusterSpec",
    "UnsupportedRuntimeError",
    "WorkDirectoryLayout",
    "assert_serializable_payload",
    "build_add_sector_models_command",
    "build_compress_mosaic_command",
    "build_concatenate_command",
    "build_make_mosaic_command",
    "build_make_mosaic_template_command",
    "build_predict_model_data_command",
    "build_regrid_image_command",
    "build_runtime_spec",
    "build_subtract_sector_models_command",
    "build_task_runner",
    "check_dask_scheduler",
    "calibrate_chunk_task",
    "calibrate_flow",
    "calibrate_payload_from_inputs",
    "concatenate_epoch_task",
    "collect_preflight_issues",
    "command_matches_fixture",
    "command_to_string",
    "concatenate_flow",
    "concatenate_payload_from_inputs",
    "collect_process_features",
    "collect_resource_issues",
    "collect_resource_request_issues",
    "collect_slurm_config_issues",
    "default_process_lifecycle_hooks",
    "default_process_operation_factories",
    "dask_scheduler_from_environment",
    "directory_record",
    "file_record",
    "image_flow",
    "image_sector_task",
    "is_output_record",
    "mosaic_flow",
    "mosaic_image_type_task",
    "mosaic_payload_from_inputs",
    "normalized_add_sector_models_command",
    "normalized_concatenate_command",
    "normalized_make_mosaic_command",
    "normalized_make_mosaic_template_command",
    "normalized_predict_model_data_command",
    "normalized_regrid_image_command",
    "normalized_subtract_sector_models_command",
    "normalize_command",
    "predict_flow",
    "predict_model_data_task",
    "predict_payload_from_inputs",
    "predict_postprocess_task",
    "preflight_execution",
    "process_flow",
    "process_steps_flow",
    "run_calibrate_chunk",
    "run_calibrate_flow",
    "run_concatenate_epoch",
    "run_concatenate_flow",
    "run_image_flow",
    "run_mosaic_flow",
    "run_mosaic_image_type",
    "run_predict_flow",
    "run_predict_model_data",
    "run_predict_postprocess",
    "run_process",
    "run_process_preflight",
    "run_process_steps",
    "run_shell_command",
    "slurm_cluster_spec",
    "validate_output_record",
    "validate_resource_request",
]
