# Copyright (C) 2021 ASTRON (Netherlands Institute for Radio Astronomy)
# SPDX-License-Identifier: GPL-3.0-or-later

# This file contains the pipelines that run on the SKAO repository of IDG, which
# is at https://gitlab.com/ska-telescope/sdp/ska-sdp-func-idg

include:
  - local: .gitlab-ci.common.yml
# Create Gitlab CI badges from CI metrics
# https://developer.skao.int/en/latest/tools/continuousintegration.html#automated-collection-of-ci-health-metrics-as-part-of-the-ci-pipeline
  - project: ska-telescope/templates-repository
    file: gitlab-ci/includes/post_step.yml

# Caching 'public' allows keeping the 'pages' output of multiple branches / MRs.
cache:
  paths:
    - public

# The SKA repo does not have a docker cache.
# We need to push the base image to the gitlab registry which requires docker:dind
prepare-base:
  stage: prepare
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}_base -f ./docker/ubuntu_20_04_base .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}_base

# The SKA repo does not have a docker cache
# We need to push the integration image to the gitlab registry which requires docker:dind
prepare-integration:
  stage: prepare
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}_integration -f ./docker/ubuntu_20_04_integration .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}_integration

prepare-gpu:
  stage: prepare
  needs: []
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}_gpu -f ./docker/ubuntu_20_04_gpu .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}_gpu

test-gpu:
  stage: test
  needs: ["prepare-gpu"]
  # This job may fail, since the k8srunner-gpu node is still experimental.
  allow_failure: true
  timeout: 10 minutes
  tags: [k8srunner-gpu]
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}_gpu
  script:
    - nvidia-smi
    - cd /idg/bin
    - for x in test-*; do echo == Running $x ==; ./$x; done

deploy-package:
  stage: publish
  # Only deploy if the tests pass
  needs: ["prepare-gpu","test-unit","test-integration","test-gpu"]
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}_gpu
  before_script:
    - apt-get update
    - apt-get install -y curl
  script:
    - cd /idg
    - |
      for pkg in idg-*.deb; do
        out=${pkg//_/-}
        out=${out/#idg-/${CI_PROJECT_NAME}-}
        out=${out/%\.deb/-ubuntu20.04.deb}
        out=${CAR_RAW_REPOSITORY_URL}/${CI_PROJECT_NAME}/$out
        echo Deploying $pkg to $out...
        curl -u ${CAR_RAW_USERNAME}:${CAR_RAW_PASSWORD} --upload-file $pkg $out
      done
  rules:
    # Only deploy for the master branch, builds for tags, or when UPLOAD_PACKAGE
    # is explicitly set.
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_TAG'
    - if: '$UPLOAD_PACKAGE'

deploy-docker:
  stage: publish
  # Only deploy if the tests pass
  needs: ["versions","test-unit","test-integration","test-gpu"]
  image: docker:stable
  services:
    - docker:dind
  variables:
    PIPELINE_IMAGE: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}_gpu
    CAR_IMAGE: ${CAR_OCI_REGISTRY_HOST}/${CI_PROJECT_NAME}/idg-cuda:${IDG_VERSION}
  script:
    - echo Deploying GPU docker image to ${CAR_IMAGE}
    - echo ${CI_REGISTRY_PASSWORD} | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - echo ${CAR_OCI_REGISTRY_PASSWORD} | docker login --username ${CAR_OCI_REGISTRY_USERNAME} --password-stdin ${CAR_OCI_REGISTRY_HOST}
    - docker pull ${PIPELINE_IMAGE}
    - docker tag ${PIPELINE_IMAGE} ${CAR_IMAGE}
    - docker push ${CAR_IMAGE}
  rules:
    # Only deploy for the master branch, builds for tags, or when UPLOAD_PACKAGE
    # is explicitly set.
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_TAG'
    - if: '$UPLOAD_PACKAGE'

pages:
  stage: pages
  needs: ["test-unit"]
  image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}_base
  script:
    - echo Deploying GitLab pages to $CI_PAGES_URL/$CI_COMMIT_REF_SLUG
    - mkdir -p public/$CI_COMMIT_REF_SLUG
    - cd public/$CI_COMMIT_REF_SLUG
    - gcovr -j$(($(nproc)/2 > 0 ? $(nproc)/2:1)) -r ../../ -a ../../build/run-unit.json --html-details index.html
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    paths:
      - public
    expire_in: 1 week
