# Copyright (C) 2022 ASTRON (Netherlands Institute for Radio Astronomy)
# SPDX-License-Identifier: GPL-3.0-or-later

# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - cmake
    - doxygen
    - libfftw3-dev # IDG always requires FFTW3.
    - liblapacke-dev # IDG always requires LAPACK.
    - ninja-build
  jobs:
    pre_build:
      # Build doxygen documentation
      - mkdir build
      - cmake -S . -B build -G Ninja
      - cd build && ninja doxygen

sphinx:
  configuration: doc/conf.py

python:
  install:
    - requirements: doc/requirements.txt
