"""Operation-level Prefect flows."""

from rapthor.execution.flows.concatenate import (
    build_concatenate_command,
    concatenate_epoch_task,
    concatenate_flow,
    concatenate_payload_from_inputs,
    normalized_concatenate_command,
    run_concatenate_epoch,
    run_concatenate_flow,
)
from rapthor.execution.flows.mosaic import (
    build_compress_mosaic_command,
    build_make_mosaic_command,
    build_make_mosaic_template_command,
    build_regrid_image_command,
    mosaic_flow,
    mosaic_image_type_task,
    mosaic_payload_from_inputs,
    normalized_make_mosaic_command,
    normalized_make_mosaic_template_command,
    normalized_regrid_image_command,
    run_mosaic_flow,
    run_mosaic_image_type,
)
from rapthor.execution.flows.predict import (
    build_add_sector_models_command,
    build_predict_model_data_command,
    build_subtract_sector_models_command,
    normalized_add_sector_models_command,
    normalized_predict_model_data_command,
    normalized_subtract_sector_models_command,
    predict_flow,
    predict_model_data_task,
    predict_payload_from_inputs,
    predict_postprocess_task,
    run_predict_flow,
    run_predict_model_data,
    run_predict_postprocess,
)

__all__ = [
    "build_add_sector_models_command",
    "build_concatenate_command",
    "build_compress_mosaic_command",
    "build_make_mosaic_command",
    "build_make_mosaic_template_command",
    "build_predict_model_data_command",
    "build_regrid_image_command",
    "build_subtract_sector_models_command",
    "concatenate_epoch_task",
    "concatenate_flow",
    "concatenate_payload_from_inputs",
    "mosaic_flow",
    "mosaic_image_type_task",
    "mosaic_payload_from_inputs",
    "normalized_concatenate_command",
    "normalized_make_mosaic_command",
    "normalized_make_mosaic_template_command",
    "normalized_add_sector_models_command",
    "normalized_predict_model_data_command",
    "normalized_regrid_image_command",
    "normalized_subtract_sector_models_command",
    "predict_flow",
    "predict_model_data_task",
    "predict_payload_from_inputs",
    "predict_postprocess_task",
    "run_concatenate_epoch",
    "run_concatenate_flow",
    "run_mosaic_flow",
    "run_mosaic_image_type",
    "run_predict_flow",
    "run_predict_model_data",
    "run_predict_postprocess",
]
