"""Operation-level Prefect flows.

This broad flow facade is kept for migration-era compatibility. New code should
prefer imports from the concrete flow module that owns the behaviour.
"""

from rapthor.execution.flows.calibrate import (
    calibrate_chunk_task,
    calibrate_flow,
    run_calibrate_flow,
)
from rapthor.execution.flows.concatenate import (
    build_concatenate_command,
    concatenate_epoch_task,
    concatenate_flow,
    concatenate_payload_from_inputs,
    normalized_concatenate_command,
    run_concatenate_epoch,
    run_concatenate_flow,
)
from rapthor.execution.flows.image import (
    image_flow,
    image_sector_task,
    run_image_flow,
)
from rapthor.execution.flows.mosaic import (
    build_compress_mosaic_command,
    build_make_mosaic_command,
    build_make_mosaic_template_command,
    build_regrid_image_command,
    mosaic_flow,
    mosaic_image_type_task,
    mosaic_payload_from_inputs,
    normalized_make_mosaic_command,
    normalized_make_mosaic_template_command,
    normalized_regrid_image_command,
    run_mosaic_flow,
    run_mosaic_image_type,
)
from rapthor.execution.flows.predict import (
    build_add_sector_models_command,
    build_predict_model_data_command,
    build_subtract_sector_models_command,
    normalized_add_sector_models_command,
    normalized_predict_model_data_command,
    normalized_subtract_sector_models_command,
    predict_flow,
    predict_model_data_task,
    predict_payload_from_inputs,
    predict_postprocess_task,
    run_predict_flow,
    run_predict_model_data,
    run_predict_postprocess,
)
from rapthor.execution.flows.process import (
    SUPPORTED_PROCESS_FEATURES,
    ProcessLifecycleHooks,
    ProcessOperationFactories,
    collect_process_features,
    default_process_lifecycle_hooks,
    default_process_operation_factories,
    process_flow,
    process_steps_flow,
    run_process,
    run_process_preflight,
    run_process_steps,
)

__all__ = [
    "build_add_sector_models_command",
    "build_concatenate_command",
    "build_compress_mosaic_command",
    "build_make_mosaic_command",
    "build_make_mosaic_template_command",
    "build_predict_model_data_command",
    "build_regrid_image_command",
    "build_subtract_sector_models_command",
    "calibrate_chunk_task",
    "calibrate_flow",
    "concatenate_epoch_task",
    "concatenate_flow",
    "concatenate_payload_from_inputs",
    "default_process_operation_factories",
    "image_flow",
    "image_sector_task",
    "mosaic_flow",
    "mosaic_image_type_task",
    "mosaic_payload_from_inputs",
    "normalized_concatenate_command",
    "normalized_make_mosaic_command",
    "normalized_make_mosaic_template_command",
    "normalized_add_sector_models_command",
    "normalized_predict_model_data_command",
    "normalized_regrid_image_command",
    "normalized_subtract_sector_models_command",
    "predict_flow",
    "predict_model_data_task",
    "predict_payload_from_inputs",
    "predict_postprocess_task",
    "process_flow",
    "process_steps_flow",
    "ProcessLifecycleHooks",
    "ProcessOperationFactories",
    "SUPPORTED_PROCESS_FEATURES",
    "collect_process_features",
    "run_process",
    "run_process_preflight",
    "run_calibrate_flow",
    "run_concatenate_epoch",
    "run_concatenate_flow",
    "run_image_flow",
    "run_mosaic_flow",
    "run_mosaic_image_type",
    "run_predict_flow",
    "run_predict_model_data",
    "run_predict_postprocess",
    "run_process_steps",
    "default_process_lifecycle_hooks",
]
